---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull shubhamg02/calculatordevops
      docker_image:
        name: shubhamg02/calculatordevops
        source: pull
#    - name: Copy jar file to home directory
#      copy:
#        src: ./target/Lab3Junit-1.0-SNAPSHOT.jar
#        dest: ~/
#        mode: '0755'